# Command: git-history
# Description: View recent git commits and changed files
# Category: git
# Version: 2
# Author: iFlow

description = "查看最近的 git 提交和修改的文件"

prompt = """
查看最近 {{args}} 个 git 提交及其修改的文件。

如果未指定数量，默认显示最近 3 个提交。

请使用 git 命令获取提交历史和文件变更信息，并以清晰的格式展示。

## 推荐的 git 命令：

```bash
# 获取最近 N 个提交（N={{args}}，如果为空则使用 3）
git log -n N --name-status --pretty=format:"%h - %s (%cr)"
```

## 输出格式：

```
## Recent Commits (最近 N 个提交)

### Commit 1: <commit-hash> - <message> (<time ago>)
**Files changed:**
- Modified: file1.rs
- Added: file2.rs
- Deleted: file3.rs

### Commit 2: <commit-hash> - <message> (<time ago>)
**Files changed:**
- Modified: file4.rs
- Modified: file5.rs

...
```
"""