[package]
name = "transaction_callback"
version = "0.1.0"
edition = "2021"

[dependencies]
sol-trade-sdk = { path = "../../" }
anyhow = "1.0"
tokio = { version = "1", features = ["full"] }
solana-sdk = "3.0.0"
solana-commitment-config = "3.0.0"
serde_json = "1.0"
futures = "0.3"